pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    // Эта строка заставляет проект брать репозитории только отсюда
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal() // Обязательно для Allure
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "FMHAndroid"
include ':app'